config/routes.rb
Rails.application.routes.draw do
  root 'static_pages#home'
  get 'team'   => 'static_pages#team'
  get 'social'   => 'static_pages#social'
  get 'blog'  => 'static_pages#blog'
  get 'projects'  => 'static_pages#projects'
  get 'signup'  => 'users#new'
  resources :users
end

app/models/user.rb
class User < ActiveRecord::Base
  before_save { self.email = email.downcase }
  validates :name, presence: true, length: { maximum: 50 }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, length: { maximum: 255 },
                    format: { with: VALID_EMAIL_REGEX },
                    uniqueness: { case_sensitive: false }
  has_secure_password
  validates :password, presence: true, length: { minimum: 6 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
    ##configure the BitBucket Feed##
    #use the url of the rss feed you want
    url= "https://bitbucket.org/herbo4/cognitive-dynamics/rss?token=922db50ce656e58771d08c34d4123a4d"
    #declare a symbol to reference the feed from using Feedjira
    @recent =  Feedjira::Feed.fetch_and_parse url
  end

  def blog
  end

  def projects
  end

  def team
  end

  def social
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  
  def show
    @user = User.find(params[:id])
  end
  
  def new
    @user = User.new
  end
end

app/helpers/application_helper.rb
module ApplicationHelper

  # Returns the full title on a per-page basis.
  def full_title(page_title = '')
    base_title = "Cognitive Dynamics"
    if page_title.empty?
      base_title
    else
      page_title + " | " + base_title
    end
  end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper

  # Returns the Gravatar for the given user.
  def gravatar_for(user)
    gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
    gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}"
    image_tag(gravatar_url, alt: user.name, size:'140x140', class: "gravatar img-responsive img-circle")
  end
end

app/views/layouts/_bitbucket.html.erb
<div class="row">
  <div class="table-responsive col-xs-12 col-sm-12" style="padding-left: 0px; padding-right: 0px; border-top: none;">
    <table class='table table-striped table-bordered table-condensed'>
    <% @recent.entries[0..5].each do |entry| %>
      <% 
      #split the bitbucket url up so we can extract the username
      link_array = entry.url.split('/')
      username = link_array[3]
      
      #create links to the user whose commit is currently being iterated over, as well as their avatar and alt text for their avatar
      link_to_avatar = "https://bitbucket.org/account/" + username + "/avatar/48/?ts=0"
      alt_text = username + "'s avatar"
      link_to_account = "https://bitbucket.org/" + username
      
      %>
      <tr>
        <td>
          <%= 
          #generate the bitbucket avatar image and a link ot the user's bitbucket account
          link_to image_tag(link_to_avatar, size:'25x25', alt: alt_text),  link_to_account 
          %>
        </td>
        <td>
          <%= 
          #list the latest commit link via its id
          link_to entry.url.last(12).to_s, entry.url 
          %>
        </td>
        <td>
          <%= 
          #give the title of the commit as a brief description
          entry.title 
          %>
        </td>
      </tr>
    <% end %>
    </table>
  </div>
</div>

app/views/layouts/_blogpost.html.erb
<div class="col-xs-12 col-sm-6">
    <h2>Blognitive Dynamics - Designing the Site</h2>
    <div class="row">
        <div class="col-xs-12">
            <%= image_tag("WebLayout.jpg", alt: "Site Layout Draft", class:"img-responsive") %>
        </div>
        <div class="col-xs-12">
            <h3>7/30/2015</h3>
            Kyle and I met a few weeks ago to plan the site, and this is a picture of our collaboration. We hope to have a finished site before the end of August, and after that we'll have tons of content to throw up here.
        </div>
    </div>
</div>

app/views/layouts/_footer.html.erb
<footer class="footer">
</footer>

app/views/layouts/_header.html.erb
<header>
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#collapse-me" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        Menu
      </button>
    </div>
    <nav>
      <div class="collapse navbar-collapse col-xs-12 navbar-fixed-bottom" id="collapse-me">
        <ul class="nav nav-justified">
          <li class="<%= 'active' if current_page?(root_path) %>"><%= link_to "HOME",  root_path  %></li>
          <li class="<%= 'active' if current_page?(blog_path) %>"><%= link_to "BLOG",  blog_path  %></li>
          <li class="<%= 'active' if current_page?(social_path) %>"><%= link_to "SOCIAL",   social_path %></li>
          <li class="<%= 'active' if current_page?(projects_path) %>"><%= link_to "PROJECTS",   projects_path %></li>
          <li class="<%= 'active' if current_page?(team_path) %>"><%= link_to "TEAM", team_path %></li>
        </ul>
      </div>
    </nav>
  </div>
</header>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
  <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
  </script>
<![endif]-->

app/views/layouts/_twitter.html.erb
<div class="row">
    <div class="col-xs-12 col-sm-12">
        <a class="twitter-timeline" data-dnt="true" href="https://twitter.com/RememberTuvix/lists/cognitive-dynamics" data-widget-id="631868736463589378">Tweets from https://twitter.com/RememberTuvix/lists/cognitive-dynamics</a>
<script>!function(d,s,id){var js,fjs=d.getElementsByTagName(s)[0],p=/^http:/.test(d.location)?'http':'https';if(!d.getElementById(id)){js=d.createElement(s);js.id=id;js.src=p+"://platform.twitter.com/widgets.js";fjs.parentNode.insertBefore(js,fjs);}}(document,"script","twitter-wjs");</script>
    </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield(:title)) %></title>
    <%= stylesheet_link_tag 'application', media: 'all',
                                           'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
    <%= render 'layouts/shim' %>
    <meta name="viewport" content="width=device-width, initial-scale=1">
  </head>
  <body>
    <div class="container">
      <div class="row">
        <div class="col-xs-12">
          <h1><%= link_to image_tag("Logo.png", alt: "Welcome to the Cognitive Dynamics Web Site", class:"img-responsive"),  root_path %></h1>
          <%= render 'layouts/header' %>
        </div>
      </div>
    </div>
    <div class="container">
        <%= yield %>
        <%= render 'layouts/footer' %>
    </div>
  </body>
</html>

app/views/static_pages/blog.html.erb
<% provide(:title, "Blog") %>

app/views/static_pages/home.html.erb
<div class="container">
    <div class="row">
        <%= render 'layouts/blogpost' %>
        <div class="col-xs-12 col-sm-6 visible-xs">
        <hr>
        </div>
        <div class="col-xs-12 col-sm-5 col-sm-offset-1">
            <%= render 'layouts/twitter' %>
            <hr>
            <h2>Project Updates</h2>
            <%= render 'layouts/bitbucket' %>
        </div>
    </div>
</div>

app/views/static_pages/projects.html.erb
<% provide(:title, "Projects") %>

app/views/static_pages/social.html.erb
<% provide(:title, "Social Media") %>

app/views/static_pages/team.html.erb
<% provide(:title, "Dev Team") %>

app/views/users/new.html.erb
<% provide(:title, 'Sign up') %>
<h1>Sign up</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for(@user) do |f| %>
      <%= f.label :name %>
      <%= f.text_field :name %>

      <%= f.label :email %>
      <%= f.email_field :email %>

      <%= f.label :password %>
      <%= f.password_field :password %>

      <%= f.label :password_confirmation, "Confirmation" %>
      <%= f.password_field :password_confirmation %>

      <%= f.submit "Create my account", class: "btn btn-primary" %>
    <% end %>
  </div>
</div>

app/views/users/show.html.erb
<% provide(:title, @user.name) %>
<div class="row">
  <div class="col-xs-12 col-md-6">
    <div class="user_info">
      <div class="row">
        <div class="col-xs-3 col-sm-4">
          <%= gravatar_for @user %>
        </div>
        <div class="col-xs-9 col-sm-8">
          <div class="row">
            <%= @user.name %>
          </div>
          <div class="row">
            <%= @user.email %>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>